# Generated by Django 5.1.2 on 2024-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=130)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('mobile', 'mobile')], default='mobile', max_length=20),
        ),
    ]
