# Generated by Django 5.1.2 on 2024-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_modelvideo_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('pc', 'pc'), ('mobile', 'mobile'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
