# Generated by Django 5.1.2 on 2024-10-21 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_modelvideo_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='month',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='title',
            field=models.CharField(choices=[('информационный', 'informational'), ('образовательный', 'educational'), ('развлекательный', 'entertaining')], default='информационный', max_length=50),
        ),
    ]
