# Generated by Django 5.1.2 on 2024-10-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_modelvideo_date_alter_modelvideo_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('развлекательный', 'entertaining'), ('образовательный', 'educational'), ('информационный', 'informational')], default='информационный', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
