# Generated by Django 5.1.2 on 2024-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_modelvideo_genre_alter_modelvideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='img',
            field=models.ImageField(default='naruto', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('образовательный', 'educational'), ('информационный', 'informational'), ('развлекательный', 'entertaining')], default='информационный', max_length=50),
        ),
    ]
