# Generated by Django 5.1.2 on 2024-10-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_modelvideo_img_alter_modelvideo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('развлекательный', 'entertaining'), ('информационный', 'informational'), ('образовательный', 'educational')], default='информационный', max_length=50),
        ),
    ]
