# Generated by Django 5.1.2 on 2024-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_modelvideo_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvideo',
            name='img',
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('informational', 'informational'), ('entertaining', 'entertaining'), ('educational', 'educational')], default='informational', max_length=50, null=True),
        ),
    ]
