# Generated by Django 5.1.2 on 2024-10-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_modelvideo_img_alter_modelvideo_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('informational', 'informational'), ('educational', 'educational'), ('entertaining', 'entertaining')], default='informational', max_length=50, null=True),
        ),
    ]
