# Generated by Django 5.1.2 on 2024-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_modelvideo_genre_alter_modelvideo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('educational', 'educational'), ('informational', 'informational'), ('entertaining', 'entertaining')], default='informational', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='image',
            field=models.ImageField(default='naruto', null=True, upload_to='images'),
        ),
    ]
