# Generated by Django 5.1.2 on 2024-10-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_modelvideo_genre_alter_modelvideo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvideo',
            name='image',
        ),
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(choices=[('informational', 'informational'), ('educational', 'educational'), ('entertaining', 'entertaining')], default='informational', max_length=50, null=True),
        ),
    ]
