# Generated by Django 5.1.2 on 2024-10-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_modelvideo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
