# Generated by Django 5.1.2 on 2024-10-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_modelvideo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvideo',
            name='date',
        ),
    ]
