# Generated by Django 5.1.2 on 2024-10-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_remove_modelvideo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvideo',
            name='image',
        ),
    ]
