# Generated by Django 5.1.2 on 2024-10-22 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_remove_modelvideo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
