# Generated by Django 5.1.2 on 2024-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_modelvideo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
