# Generated by Django 5.1.2 on 2024-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('group', models.CharField(choices=[('pc', 'pc'), ('accessories', 'accessories'), ('mobile', 'mobile'), ('notebook', 'notebook')], default='mobile', max_length=20)),
            ],
        ),
    ]
